ALTER TABLE cus_point
Add Actual_value number



DROP TABLE NCCONSTANT
CREATE TABLE NCCONSTANT(CONSTANTID 	NUMBER NOT NULL, TYPE VARCHAR2(30) NOT NULL, DESCRIPTION VARCHAR2(255) NOT NULL, SYSTEMTYPE NUMBER NOT NULL, USAGE NUMBER NULL)

COMMENT ON TABLE NCCONSTANT IS 'Store all constants of NCMS that used in combo boxes'

COMMENT ON COLUMN NCCONSTANT.DESCRIPTION IS 'Become a Type when it is System Type'

COMMENT ON COLUMN NCCONSTANT.USAGE IS 'NCMS/Call Log'

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(0, 'UserRole', 'Administrators', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(1, 'UserRole', 'Creator', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(2, 'UserRole', 'PQA', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(3, 'UserRole', 'Reviewer', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(4, 'UserRole', 'Assignee', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(5, 'Status', 'Opened', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(6, 'Status', 'Cancelled', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(7, 'Status', 'Assigned', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(8, 'Status', 'Pending', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(9, 'Status', 'Closed', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(10, 'System', 'NCLevel', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(11, 'System', 'DetectedBy', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(12, 'System', 'NCType', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(13, 'System', 'Process', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(14, 'System', 'TypeOfCause', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(15, 'System', 'TypeOfAction', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(16, 'System', 'KPA', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(17, 'System', 'ISOClause', 1, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(18, 'NCLevel', 'Company', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(19, 'NCLevel', 'Group/Department', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(20, 'NCLevel', 'Project', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(21, 'NCType', 'Non Conformity', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(22, 'NCType', 'Observation', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(23, 'NCType', 'Customer Complaint', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(25, 'NCType', 'Defect Prevention', 0, 2)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(28, 'DetectedBy', 'Quality control', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(29, 'DetectedBy', 'FSOFT intenal audit', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(30, 'DetectedBy', 'External audit', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(31, 'DetectedBy', 'Ad hoc', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(32, 'DetectedBy', 'Customer feedback during project time', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(33, 'DetectedBy', 'Customer survey', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(34, 'TypeOfCause', 'Not be institutionalized', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(35, 'TypeOfCause', 'Improper document', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(36, 'TypeOfCause', 'Not be trained', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(37, 'TypeOfCause', 'Inadequate training', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(38, 'TypeOfCause', 'Not be implemented', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(39, 'TypeOfCause', 'Inadequate implementation', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(40, 'TypeOfAction', 'Institutionalize', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(41, 'TypeOfAction', 'Document', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(42, 'TypeOfAction', 'Conduct training', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(43, 'TypeOfAction', 'Full implementation', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(44, 'TypeOfAction', 'Re-training', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(45, 'Process', 'Contract management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(46, 'Process', 'Requirement', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(47, 'Process', 'Design', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(48, 'Process', 'Coding', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(49, 'Process', 'Deployment', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(50, 'Process', 'Customer Support', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(51, 'Process', 'Test', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(52, 'Process', 'Configuration Management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(53, 'Process', 'Project Management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(54, 'Process', 'Subcontract Management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(80, 'ISOClause', '7.1', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(81, 'ISOClause', '4.2.3', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(82, 'ISOClause', '4.2.4', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(83, 'ISOClause', '5.5.3', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(84, 'ISOClause', '6.2.2', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(85, 'ISOClause', '7.2.2', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(86, 'ISOClause', '7.3.4', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(87, 'ISOClause', '7.3.6', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(88, 'ISOClause', '7.3.7', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(89, 'ISOClause', '7.5.1', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(90, 'ISOClause', '7.5.3', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(91, 'ISOClause', '8.2.3', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(92, 'ISOClause', '8.2.4', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(93, 'Process', 'Administration', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(94, 'Process', 'Document Control', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(95, 'Process', 'Staff Management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(96, 'Process', 'IS Management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(97, 'Process', 'Quality Control', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(98, 'Process', 'Training', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(99, 'TypeOfAction', 'Re-training, more control', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(100, 'KPA', 'PP', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(101, 'KPA', 'PT', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(102, 'KPA', 'SM', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(103, 'KPA', 'RM', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(104, 'KPA', 'QA', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(105, 'KPA', 'CM', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(106, 'KPA', 'PF', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(107, 'KPA', 'PD', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(108, 'KPA', 'IM', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(109, 'KPA', 'TP', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(110, 'KPA', 'PE', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(111, 'KPA', 'IC', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(112, 'KPA', 'PR', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(113, 'KPA', 'PA', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(114, 'KPA', 'QM', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(115, 'KPA', 'DP', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(116, 'KPA', 'TI', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(121, 'ISOClause', 'Defect Prevention', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(122, 'DetectedBy', 'DP Team', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(123, 'Process', 'Prevention', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(140, 'ISOClause', '8.4', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(160, 'ISOClause', '8.5', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(180, 'ISOClause', '7.4', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(181, 'ISOClause', '7.2', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(200, 'Process', 'Quality Planning', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(220, 'Process', 'Technology management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(240, 'System', 'Repeat', 1, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(241, 'Repeat', '1-High', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(242, 'Repeat', '2-Medium', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(243, 'Repeat', '3-Low', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(251, 'Process', 'Requirement', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(252, 'Process', 'Design', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(253, 'Process', 'Coding', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(254, 'Process', 'Contract management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(255, 'Process', 'Deployment', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(256, 'Process', 'Customer Support', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(257, 'Process', 'Test', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(258, 'Process', 'Configuration Management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(259, 'Process', 'Project Management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(260, 'Process', 'Quality Planning', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(261, 'Process', 'Subcontract Management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(262, 'Process', 'Quality Control', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(263, 'Process', 'Internal Audit', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(264, 'Process', 'Correction', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(265, 'Process', 'Management Review', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(266, 'Process', 'Recruitment', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(267, 'Process', 'Training', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(268, 'Process', 'Document Control', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(269, 'Process', 'IS Management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(270, 'Process', 'Staff Management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(271, 'Process', 'Collaborator Management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(272, 'Process', 'Student Management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(273, 'Process', 'Administration', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(274, 'Process', 'Facility Management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(275, 'Process', 'Retirement', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(276, 'Process', 'Other', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(277, 'Process', 'Technology management', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(278, 'Process', 'Prevention', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(280, 'TypeOfAction', 'Re-training', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(281, 'NCLevel', 'Project', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(300, 'ISOClause', '5.4.1', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(320, 'Process', 'Collaborator Management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(321, 'Process', 'Facility Management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(322, 'Process', 'Internal Audit', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(323, 'Process', 'Retirement', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(324, 'Process', 'Correction', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(325, 'Process', 'Student Management', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(326, 'Process', 'Management Review', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(327, 'Process', 'Other', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(328, 'Process', 'Recruitment', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(340, 'TypeOfAction', 'Institutionalization', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(341, 'TypeOfAction', 'Training', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(342, 'TypeOfAction', 'Implementation', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(343, 'TypeOfAction', 'Studying', 0, 1)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(360, 'ISOClause', '7.5.2', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(420, 'NCType', 'Problem', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(580, 'ISOClause', '8.5.2', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(620, 'ISOClause', '8.5.1', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(980, 'ISOClause', '7.3.3', 0, 0)

INSERT INTO NCCONSTANT(CONSTANTID, TYPE, DESCRIPTION, SYSTEMTYPE, USAGE)  VALUES(981, 'ISOClause', '6.2.1', 0, 0)



INSERT INTO responsibility VALUES('Developer',2,'TeamMember',10,0,'PP_DEV',0,NULL)

INSERT INTO responsibility VALUES('Tester',3,'Tester',9,1,'PP_TESTER',0,NULL)

INSERT INTO responsibility VALUES('Project Team Leader',1,'PL',12,2,'PP_PTL',0,NULL)

INSERT INTO responsibility VALUES('Project Manager',0,'PD',13,3,'PP_PM',0,NULL)

INSERT INTO responsibility VALUES('Graphic Designer',NULL,'TeamMember',NULL,4,'PP_GP_DESIGNER',0,1)

INSERT INTO responsibility VALUES('External user',NULL,'External user',NULL,5,'PP_EXT_USER',0,NULL)

INSERT INTO responsibility VALUES('Onsite-Coordinator/Bridge SE',9,'TeamMember',4,6,'PP_ONSITE_CO',0,NULL)

INSERT INTO responsibility VALUES('Quality Assurance',4,'SQA',11,7,'PP_SQA',0,NULL)

INSERT INTO responsibility VALUES('PQA',NULL,'PQA',NULL,8,'PP_PQA',0,1)

INSERT INTO responsibility VALUES('Comtor',12,'Communicator',1,9,'PP_COMTOR',0,NULL)

INSERT INTO responsibility VALUES('Architecture Designer',NULL,'TeamMember',NULL,NULL,'PP_ARC_DESIGN',0,NULL)

INSERT INTO responsibility VALUES('Business Assurance',NULL,'BA',NULL,NULL,'PP_BA',0,NULL)

INSERT INTO responsibility VALUES('Test Leader',NULL,'TeamMember',NULL,NULL,'PP_TEST_LEADER',0,NULL)

INSERT INTO responsibility VALUES('Delivey Manager',NULL,'PL',NULL,NULL,'PP_DM',0,NULL)

INSERT INTO responsibility VALUES('Customer',NULL,'Customer',NULL,NULL,'PP_CUSTOMER',0,NULL)

INSERT INTO responsibility VALUES('End User',NULL,'End User',NULL,NULL,'PP_END_USER',0,NULL)

INSERT INTO responsibility VALUES('Project Admin',NULL,'Admin',NULL,NULL,'PP_ADMIN',0,NULL)

INSERT INTO responsibility VALUES('Designer',NULL,'TeamMember',NULL,10,'PP_DESIGNER',0,NULL)

INSERT INTO responsibility VALUES('Business Analyst',7,'BA',6,12,'PP_BUZ_ANALYST',0,NULL)

INSERT INTO responsibility VALUES('Senior Manager',8,'TeamMember',5,13,'PP_SENIOR',0,NULL)

INSERT INTO responsibility VALUES('Configuration Controller',10,'TeamMember',3,14,'PP_CC',0,NULL)

INSERT INTO responsibility VALUES('DP member ',11,'TeamMember',2,15,'PP_DP',0,NULL) 



CREATE TABLE DP_MILESTONE (DP_MILESTONE_ID NUMBER NOT NULL, MILESTONE_ID NUMBER NOT NULL, DPTASKID NUMBER NOT NULL, ACTUAL NUMBER NULL) 



INSERT INTO risk_category VALUES(2,'Customer Mission and Goals',NULL)

INSERT INTO risk_category VALUES(3,'Customer Organization Management',NULL)

INSERT INTO risk_category VALUES(4,'Customer/End User',NULL)

INSERT INTO risk_category VALUES(5,'Customer Technical Organization',NULL)

INSERT INTO risk_category VALUES(6,'Project Characteristics',NULL)

INSERT INTO risk_category VALUES(7,'Project Decision Drivers',NULL)

INSERT INTO risk_category VALUES(8,'Project Development Process',NULL)

INSERT INTO risk_category VALUES(9,'Project Development and Deployment Environment',NULL)

INSERT INTO risk_category VALUES(10,'Project (Program) Management (PM)',NULL)

INSERT INTO risk_category VALUES(11,'Project Team (MS, Customer, SP)',NULL)

INSERT INTO risk_category VALUES(12,'Project Technology',NULL)

INSERT INTO risk_category VALUES(13,'Project Maintenance',NULL)

INSERT INTO risk_category VALUES(20,'Customer',1)

INSERT INTO risk_category VALUES(21,'Human resource',1)

INSERT INTO risk_category VALUES(22,'Project Characteristics',1)

INSERT INTO risk_category VALUES(23,'Project Dependencies',1)

INSERT INTO risk_category VALUES(24,'Project Infrastructure',1)

INSERT INTO risk_category VALUES(25,'Project Management',1)

INSERT INTO risk_category VALUES(26,'Project Requirement',1)

INSERT INTO risk_category VALUES(27,'Technical',1)




INSERT INTO risk_source VALUES(2,'Effect on Work Flow',2,NULL,NULL)

INSERT INTO risk_source VALUES(3,'Project Fit to Customer',2,NULL,NULL)

INSERT INTO risk_source VALUES(4,'Decision Making',3,NULL,NULL)

INSERT INTO risk_source VALUES(5,'Executive Involvement',3,NULL,NULL)

INSERT INTO risk_source VALUES(6,'Gather Customer Measures',3,NULL,NULL)

INSERT INTO risk_source VALUES(7,'Management Support',3,NULL,NULL)

INSERT INTO risk_source VALUES(8,'Organization Roles and Responsibilities',3,NULL,NULL)

INSERT INTO risk_source VALUES(9,'Organization Stability',3,NULL,NULL)

INSERT INTO risk_source VALUES(10,'Point of Involvement in Organization',3,NULL,NULL)

INSERT INTO risk_source VALUES(11,'Policies and Standards',3,NULL,NULL)

INSERT INTO risk_source VALUES(12,'Project Objectives',3,NULL,NULL)

INSERT INTO risk_source VALUES(13,'Ability for Customer to Attract and Keep Personnel',4,NULL,NULL)

INSERT INTO risk_source VALUES(14,'Hiring of Contract Staff',4,NULL,NULL)

INSERT INTO risk_source VALUES(15,'Soundness of People Management Practices',4,NULL,NULL)

INSERT INTO risk_source VALUES(16,'End User Acceptance',5,NULL,NULL)

INSERT INTO risk_source VALUES(17,'End User Experience',5,NULL,NULL)

INSERT INTO risk_source VALUES(18,'End User Involvement',5,NULL,NULL)

INSERT INTO risk_source VALUES(19,'End User Knowledge of Domain',5,NULL,NULL)

INSERT INTO risk_source VALUES(20,'End User Training Needs',5,NULL,NULL)

INSERT INTO risk_source VALUES(21,'Uniformity of End User Population',5,NULL,NULL)

INSERT INTO risk_source VALUES(22,'Project Complexity',6,NULL,NULL)

INSERT INTO risk_source VALUES(23,'Hardware Constraints',6,NULL,NULL)

INSERT INTO risk_source VALUES(24,'Requirements Stability',6,NULL,NULL)

INSERT INTO risk_source VALUES(25,'Requirements Complete and Clear',6,NULL,NULL)

INSERT INTO risk_source VALUES(26,'Customer Expectations',6,NULL,NULL)

INSERT INTO risk_source VALUES(27,'Completion Criteria ',6,NULL,NULL)

INSERT INTO risk_source VALUES(28,'Cost/Benefit Justification',6,NULL,NULL)

INSERT INTO risk_source VALUES(29,'Testability',6,NULL,NULL)

INSERT INTO risk_source VALUES(30,'Architecture Fit',6,NULL,NULL)

INSERT INTO risk_source VALUES(31,'Design Difficulty',6,NULL,NULL)

INSERT INTO risk_source VALUES(32,'Implementation Difficulty (Complexity)',6,NULL,NULL)

INSERT INTO risk_source VALUES(33,'System Dependencies',6,NULL,NULL)

INSERT INTO risk_source VALUES(34,'Reusable Components',6,NULL,NULL)

INSERT INTO risk_source VALUES(35,'Supplied Components',6,NULL,NULL)

INSERT INTO risk_source VALUES(36,'Political Influences',7,NULL,NULL)

INSERT INTO risk_source VALUES(37,'Fixed End Date',7,NULL,NULL)

INSERT INTO risk_source VALUES(38,'Done for Sake of Technology',7,NULL,NULL)

INSERT INTO risk_source VALUES(39,'Short-term Solution',7,NULL,NULL)

INSERT INTO risk_source VALUES(40,'Project Dependencies',8,NULL,NULL)

INSERT INTO risk_source VALUES(41,'Estimation Processes',8,NULL,NULL)

INSERT INTO risk_source VALUES(42,'Confidence in Estimate of Effort',8,NULL,NULL)

INSERT INTO risk_source VALUES(43,'Alternatives Analysis',8,NULL,NULL)

INSERT INTO risk_source VALUES(44,'Existing System Documentation',8,NULL,NULL)

INSERT INTO risk_source VALUES(45,'Commitment Change Process',8,NULL,NULL)

INSERT INTO risk_source VALUES(46,'Process Assurance Approach',8,NULL,NULL)

INSERT INTO risk_source VALUES(47,'Pilot  Approach',8,NULL,NULL)

INSERT INTO risk_source VALUES(48,'Project Documentation',8,NULL,NULL)

INSERT INTO risk_source VALUES(49,'Use of Defined Engineering Process',8,NULL,NULL)

INSERT INTO risk_source VALUES(50,'Early Identification of Defects',8,NULL,NULL)

INSERT INTO risk_source VALUES(51,'Defect Tracking',8,NULL,NULL)

INSERT INTO risk_source VALUES(52,'Change Control for Work Products (Configuration Management)',8,NULL,NULL)

INSERT INTO risk_source VALUES(53,'Configuration Management Plans',8,NULL,NULL)

INSERT INTO risk_source VALUES(68,'Data Migration Required',10,NULL,NULL)

INSERT INTO risk_source VALUES(69,'External Hardware or Software Interfaces',10,NULL,NULL)

INSERT INTO risk_source VALUES(70,'Tracking Project Effort and Cost',10,NULL,NULL)

INSERT INTO risk_source VALUES(71,'Team Member Availability',11,NULL,NULL)

INSERT INTO risk_source VALUES(72,'Mix of Skills',11,NULL,NULL)

INSERT INTO risk_source VALUES(73,'Team Fills Roles of MSF Model',11,NULL,NULL)

INSERT INTO risk_source VALUES(74,'Similar Project Experience',11,NULL,NULL)

INSERT INTO risk_source VALUES(75,'Experience with Project HW and SW Technology',11,NULL,NULL)

INSERT INTO risk_source VALUES(76,'Experience with Process',11,NULL,NULL)

INSERT INTO risk_source VALUES(77,'Project Status Communication',11,NULL,NULL)

INSERT INTO risk_source VALUES(78,'Training of Team',11,NULL,NULL)

INSERT INTO risk_source VALUES(79,'Team Spirit and Attitude',11,NULL,NULL)

INSERT INTO risk_source VALUES(80,'Team Productivity',11,NULL,NULL)

INSERT INTO risk_source VALUES(81,'Expertise with Project Domain',11,NULL,NULL)

INSERT INTO risk_source VALUES(82,'Use of Subcontractors to Microsoft',11,NULL,NULL)

INSERT INTO risk_source VALUES(83,'Technology Match to Project',12,NULL,NULL)

INSERT INTO risk_source VALUES(84,'Match to Standards',12,NULL,NULL)

INSERT INTO risk_source VALUES(85,'Availability of Technology Expertise',12,NULL,NULL)

INSERT INTO risk_source VALUES(86,'Maturity of Technology',12,NULL,NULL)

INSERT INTO risk_source VALUES(87,'Design Complexity',13,NULL,NULL)

INSERT INTO risk_source VALUES(88,'Support Personnel',13,NULL,NULL)

INSERT INTO risk_source VALUES(89,'Vendor Support',13,NULL,NULL)

INSERT INTO risk_source VALUES(90,'Responsibility for Support of Deliverables',13,NULL,NULL)

INSERT INTO risk_source VALUES(91,'Release Control of Deliverables',13,NULL,NULL)

INSERT INTO risk_source VALUES(101,'Unclear Acceptance Criteria',20,3,1)

INSERT INTO risk_source VALUES(102,'Unstable Customer Organization',20,NULL,1)

INSERT INTO risk_source VALUES(103,'Lack of Customer Support',20,NULL,1)

INSERT INTO risk_source VALUES(104,'Unclear Decision Making Process',20,NULL,1)

INSERT INTO risk_source VALUES(105,'Weak Customer Involvement',20,NULL,1)

INSERT INTO risk_source VALUES(106,'Inexperience Customer/End User',20,NULL,1)

INSERT INTO risk_source VALUES(107,'Unclear Acceptance criteria and process',20,NULL,2)

INSERT INTO risk_source VALUES(111,'Inexperience with Project Process',21,2,9)

INSERT INTO risk_source VALUES(112,'Inexperience with Project Technology',21,2,9)

INSERT INTO risk_source VALUES(113,'Insufficient business knowledge',21,1,9)

INSERT INTO risk_source VALUES(114,'Team Spirit and Attitude',21,NULL,9)

INSERT INTO risk_source VALUES(115,'Shortage of Human resource',21,NULL,9)

INSERT INTO risk_source VALUES(121,'Unrealistic schedules',22,5,1)

INSERT INTO risk_source VALUES(122,'Project Complexity',22,NULL,9)

INSERT INTO risk_source VALUES(123,'Data Migration Required',22,6,8)

INSERT INTO risk_source VALUES(132,'Critical Dependencies',23,2.2,9)

INSERT INTO risk_source VALUES(133,'Existing System Documentation',23,8,9)

INSERT INTO risk_source VALUES(134,'Parralell development',23,NULL,8)

INSERT INTO risk_source VALUES(135,'Vendor/External Support',23,NULL,2)

INSERT INTO risk_source VALUES(141,'Physical Facilities',24,8,8)

INSERT INTO risk_source VALUES(142,'Tools Availability',24,NULL,8)

INSERT INTO risk_source VALUES(143,'Hardware Constraints',24,NULL,2)

INSERT INTO risk_source VALUES(151,'External driven decisions forced on the project',25,1,2)

INSERT INTO risk_source VALUES(152,'Insufficient PM Experience',25,NULL,9)

INSERT INTO risk_source VALUES(161,'Unclear requirements',26,3,2)

INSERT INTO risk_source VALUES(162,'Too many requirement changes',26,4,2)

INSERT INTO risk_source VALUES(163,'Business Processes Complexity',26,NULL,2)

INSERT INTO risk_source VALUES(171,'New Technology',27,NULL,4)

INSERT INTO risk_source VALUES(172,'Not meeting performance requirements',27,1,4)

INSERT INTO risk_source VALUES(173,'Link failure or slow performance',27,NULL,34)

INSERT INTO risk_source VALUES(174,'Test Ability',27,10,7)

INSERT INTO risk_source VALUES(175,'Design Difficulty',27,6,3)

INSERT INTO risk_source VALUES(176,'Implementation Difficulty',27,8,34)

INSERT INTO risk_source VALUES(177,'Integration Complexity',27,NULL,34)

INSERT INTO risk_source VALUES(54,'Use of Blueprints',8,NULL,NULL)

INSERT INTO risk_source VALUES(55,'Physical Facilities',9,NULL,NULL)

INSERT INTO risk_source VALUES(56,'Hardware Platform',9,NULL,NULL)

INSERT INTO risk_source VALUES(57,'Tools Availability',9,NULL,NULL)

INSERT INTO risk_source VALUES(58,'Other Vendor Support',9,NULL,NULL)

INSERT INTO risk_source VALUES(59,'Disaster Recovery ',9,NULL,NULL)

INSERT INTO risk_source VALUES(60,'PM Approach',10,NULL,NULL)

INSERT INTO risk_source VALUES(61,'PM Experience',10,NULL,NULL)

INSERT INTO risk_source VALUES(62,'PM Authority',10,NULL,NULL)

INSERT INTO risk_source VALUES(63,'Support of the PM',10,NULL,NULL)

INSERT INTO risk_source VALUES(64,'Identification of Project Standards',10,NULL,NULL)

INSERT INTO risk_source VALUES(65,'Hardware Resources for Deliverables',10,NULL,NULL)

INSERT INTO risk_source VALUES(66,'Response or other Performance Factors',10,NULL,NULL)

INSERT INTO risk_source VALUES(67,'User Support Services Impact',10,NULL,NULL)




ALTER TABLE TAILORING 
ADD ACTION NUMBER

ALTER TABLE TAILORING 
ADD NOTE NUMBER




INSERT INTO parameters VALUES('CONV_LAST_UPDATE','22-SEP-09')

INSERT INTO parameters VALUES('LOCALHOST','http://localhost:9080')

INSERT INTO parameters VALUES('TIMESHEET','timesheet/TimesheetServlet')

INSERT INTO parameters VALUES('DASHBOARD','dashboard/DashboardServlet')

INSERT INTO parameters VALUES('DMS','dms/DMSServlet')

INSERT INTO parameters VALUES('NCMS','ncms/NcmsServlet')

INSERT INTO parameters VALUES('HELP','http://qahnsv-fms-test/FSOFTInsightWeb/help')

INSERT INTO parameters VALUES('VERSION','2.4.1')

INSERT INTO parameters VALUES('NORMQACTIVITYEFFORT','0.25')

INSERT INTO parameters VALUES('NORMPROCESSAUDITEFFORT','0.5')

INSERT INTO parameters VALUES('NORMPROCESSCONTROLEFFORT','2.0')

INSERT INTO parameters VALUES('LOGROOT','C:\')

INSERT INTO parameters VALUES('MAIL.SMTP.HOST','192.168.106.101')

INSERT INTO parameters VALUES('CONNECTIONSTRING','jdbc:oracle:thin:fms/fms@qahnsv-database-test:1521:fms')

INSERT INTO parameters VALUES('DAYOFVALIDATION','01-Nov-05')

INSERT INTO parameters VALUES('URL_ADDRESS','http://qahnsv-fms-test')




INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Requirement', 2, 'REQUIREMENT', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Design', 3, 'DESIGN', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Coding', 4, 'CODING', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Contract management', 1, 'CONTRACT_MANAGEMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Deployment', 5, 'DEPLOYMENT', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Customer Support', 6, 'CUSTOMER_SUPPORT', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Test', 7, 'TEST', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Configuration Management', 8, 'CONFIGURATION_MANAGEMENT', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Project Management', 9, 'PROJECT_MANEGEMENT', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Quality Planning', 10, 'QUALITY_PLANNING', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Subcontract Management', 11, 'SUBCONTRACT_MANEGEMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Quality Control', 12, 'QUALITY_CONTROL', 0, 'DMS')

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Internal Audit', 13, 'INTERNAL_AUDIT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Correction', 14, 'CORRECTION', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Management Review', 15, 'MANEGEMENT_REVIEW', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Recruitment', 16, 'RECRUITMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Training', 17, 'TRAINING', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Document Control', 18, 'DOCUMENT_CONTROL', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('IS Management', 19, 'IS_MANAGEMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Staff Management', 20, 'STAFF_MANAGEMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Collaborator Management', 21, 'COLLABORATOR_MANAGEMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Student Management', 22, 'STUDENT_MANAGEMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Administration', 23, 'ADMINISTRATION', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Facility Management', 24, 'FACILITY_MANAGEMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Retirement', 25, 'RETIREMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Other', 26, 'OTHER', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Technology management', 27, 'TECHNOLOGY_MANAGEMENT', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Prevention', 28, 'PREVENTION', 0, NULL)

INSERT INTO PROCESS(NAME, PROCESS_ID, CODE, DISABLED, APP_NAME) VALUES('Process Improvement', 29, 'PROCESS_IMPROVEMENT', 0, NULL)
